import jsPDF from "jspdf";
import "jspdf-autotable";

// Invoice PDF (for sales)
export const generateInvoicePDF = (sale, pharmacyDetails = {}) => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const purple = "#6b21a8";
  const lightPurple = "#e9d5ff";
  const darkText = "#111827";

  doc.setFillColor(purple);
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("TAX INVOICE", 105, 18, { align: "center" });

  doc.setTextColor(lightPurple);
  doc.setFontSize(24);
  doc.text("MEDICAL INVOICE", 105, 38, { align: "center" });

  doc.setTextColor(darkText);
  doc.setFontSize(11);
  doc.text(pharmacyDetails.name || "Vishwas Medical", 20, 55);
  doc.text(pharmacyDetails.address || "Church Street, Bengaluru - 560001", 20, 62);
  doc.text(`Phone: ${pharmacyDetails.phone || "+91-XXXXXXXXXX"}`, 20, 69);

  doc.setFillColor(lightPurple);
  doc.rect(10, 85, 190, 12, "F");

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Patient Details", 15, 93);
  doc.setFont("helvetica", "normal");
  doc.text(`Name: ${sale.customer?.name || "Walk-in Patient"}`, 15, 103);
  doc.text(`Phone: ${sale.customer?.phone || "—"}`, 15, 110);

  const tableColumn = ["S.No", "Item", "Qty", "Rate", "Amount"];
  const tableRows = sale.items.map((item, index) => {
    const prodName = item.name || item.product?.itemName || item.product?.Name || "Unknown Medicine";
    const amount = (item.price * item.quantity).toFixed(2);
    return [
      index + 1,
      prodName,
      item.quantity,
      `₹${item.price.toFixed(2)}`,
      `₹${amount}`,
    ];
  });

  doc.autoTable({
    startY: 125,
    head: [tableColumn],
    body: tableRows,
    theme: "grid",
    headStyles: { fillColor: purple, textColor: [255, 255, 255], fontStyle: "bold" },
    styles: { fontSize: 10, cellPadding: 3 },
  });

  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFillColor(purple);
  doc.rect(130, finalY, 70, 10, "F");
  doc.setTextColor(255);
  doc.text("Total Amount", 135, finalY + 7);
  doc.setTextColor(darkText);
  doc.text(`₹${sale.totalAmount?.toFixed(2) || "0.00"}`, 175, finalY + 7, { align: "right" });

  return doc.output("blob");
};

// Order PDF (cleaned up, no current stock column)
export const generateOrderPDF = (orderItems, pharmacyDetails = {}) => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const blue = "#1e40af";
  const darkText = "#111827";

  doc.setFillColor(blue);
  doc.rect(0, 0, 210, 35, "F");
  doc.setTextColor(255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("STOCK ORDER REQUEST", 105, 22, { align: "center" });
  doc.setFontSize(12);
  doc.text("Vishwas Medical", 105, 32, { align: "center" });

  doc.setTextColor(darkText);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("From:", 20, 50);
  doc.text(pharmacyDetails.name || "Vishwas Medical", 20, 58);
  doc.text(pharmacyDetails.address || "Shivamogga, Karnataka", 20, 65);
  doc.text(`Phone: ${pharmacyDetails.phone || "Your Phone Number Here"}`, 20, 72);
  doc.text(`Date: ${new Date().toLocaleDateString("en-IN")}`, 20, 79);

  const tableColumn = ["S.No", "Product Name", "Supplier", "Order Qty"];

  const tableRows = orderItems.map((item, index) => [
    index + 1,
    item.itemName || item.Name || "—",
    item.stockBroughtBy || "Unknown",
    item.orderQty === "" || item.orderQty == null ? "—" : item.orderQty,
  ]);

  doc.autoTable({
    startY: 90,
    head: [tableColumn],
    body: tableRows,
    theme: "grid",
    headStyles: { fillColor: blue, textColor: [255, 255, 255], fontStyle: "bold", halign: "center" },
    styles: { fontSize: 10, cellPadding: 4, overflow: "linebreak", halign: "left" },
    columnStyles: {
      0: { cellWidth: 15, halign: "center" },
      1: { cellWidth: 90 },
      2: { cellWidth: 55 },
      3: { cellWidth: 30, halign: "center" },
    },
    margin: { top: 90, left: 20, right: 20 },
  });

  const finalY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(11);
  doc.text("Kindly supply the above mentioned quantities at the earliest.", 20, finalY);
  doc.text("Thank you!", 20, finalY + 10);

  doc.setFontSize(9);
  doc.setTextColor("#666666");
  doc.text("Generated by Vishwas Medical Inventory System", 105, 280, { align: "center" });

  return doc.output("blob");
};