export const generateOrderPDF = (orderItems, pharmacyDetails = {}) => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const blue = "#1e40af";
  const darkText = "#111827";

  doc.setFillColor(blue);
  doc.rect(0, 0, 210, 35, "F");
  doc.setTextColor(255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("STOCK ORDER REQUEST", 105, 22, { align: "center" });
  doc.setFontSize(12);
  doc.text("Vishwas Medical", 105, 32, { align: "center" });

  doc.setTextColor(darkText);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("From:", 20, 50);
  doc.text("Vishwas Medical", 20, 58);
  doc.text("Shivamogga, Karnataka", 20, 65);
  doc.text("Phone: Your Phone Number Here", 20, 72);
  doc.text(`Date: ${new Date().toLocaleDateString("en-IN")}`, 20, 79);

  const tableColumn = ["S.No", "Product Name", "Supplier", "Order Qty"];

  const tableRows = orderItems.map((item, index) => [
    index + 1,
    item.Name || "—",
    item.stockBroughtBy || "Unknown",
    item.orderQty === "" || item.orderQty == null || item.orderQty === 0 ? "—" : item.orderQty,
  ]);

  doc.autoTable({
    startY: 90,
    head: [tableColumn],
    body: tableRows,
    theme: "grid",
    headStyles: { fillColor: blue, textColor: [255, 255, 255], fontStyle: "bold", halign: "center" },
    styles: { fontSize: 10, cellPadding: 4, overflow: "linebreak", halign: "left" },
    columnStyles: {
      0: { cellWidth: 15, halign: "center" },
      1: { cellWidth: 90 },
      2: { cellWidth: 55 },
      3: { cellWidth: 30, halign: "center" },
    },
    margin: { top: 90, left: 20, right: 20 },
  });

  const finalY = doc.lastAutoTable.finalY + 15;

  doc.setFontSize(11);
  doc.text("Kindly supply the above mentioned quantities at the earliest.", 20, finalY);
  doc.text("Thank you!", 20, finalY + 10);

  doc.setFontSize(9);
  doc.setTextColor("#666666");
  doc.text("Generated by Vishwas Medical Inventory System", 105, 280, { align: "center" });

  return doc.output("blob");
};
